name: Build UnlimitedBooks Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build the mod
      run: ./gradlew build

    - name: Upload built mod
      uses: actions/upload-artifact@v3.1.2
      with:
        name: UnlimitedBooksMod
        path: build/libs/*.jar
