name: Build UnlimitedBooks Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Archive JAR
      run: |
        mkdir -p artifacts
        cp build/libs/*.jar artifacts/

    - name: Upload artifact manually
      uses: actions/upload-artifact@v3
      with:
        name: UnlimitedBooksMod
        path: artifacts/
